language: rust
rust:
  - stable
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - rustup target add thumbv7em-none-eabihf
  - cargo build --verbose
  - cargo build --release --verbose
notifications:
  email:
    on_success: never
